- tests/BOASDK.test.ts
- tests/sdk.test.ts
It was implemented using the package `axios` and `async/await`.
Related to bpfkorea/stoa#30
> Add the ability to test requests and responses to data using the local network

- src/index.ts
- src/modules/data/PreImage.ts
- src/modules/data/Validator.ts
- src/modules/net/BOAClient.ts
- src/modules/net/Request.ts
- src/modules/utils/json.ts
- tests/BOASDK.test.ts
I made an SDK function that connects to the Stoa server and requests and receives data using the http protocol.
In typescript, these functions are asynchronous.
In other words, the data does not come as soon as the request is made. The data arrive after a certain period of time.
TypeScript is written under the condition that it uses only a single CPU. Therefore, responses to the data can be received through callback or `Promise`.
I used a more efficient `Promise` here.
And I wrote the test code using `async / await`.
Related to bpfkorea/stoa#30
> Implement getAllValidators, getValidator in SDK

- src/modules/net/Request.ts
'User-Agent' could not be changed in the browser's SDK
Related to #23
> Remove the 'User-Agent' that is currently not needed.

- src/modules/data/Hash.ts
- src/modules/data/PublicKey.ts
- src/modules/net/BOAClient.ts
- src/modules/utils/CRC16.ts
- tests/BOAClient.test.ts
The link connected two lines into one.
Change link to commit hash instead of branch name
#Relates to #30
> Fix links to Agora sources in a document

- src/modules/net/BOAClient.ts
- tests/BOAClient.test.ts
It is applied to avoid changing the return value from the user's perspective.
This function is likely to change in the future and will communicate with Stoa, so it should be processed asynchronously.
> Apply Promise asynchronous to the function getHeightAt

- src/index.ts
- src/modules/net/Request.ts
- tests/BOAClient.test.ts
To support different versions of SDK Clients in Agora, I added information from SDK to the header.
> Add information of SDK to HTTP header

- tests/BOAClient.test.ts
- tests/Hash.test.ts
I replaced a deprecated function with an available function
`assert.equal` is a deprecated function, and the alternative function is `assert.strictEqual`.
> Replace deprecated functions with available functions

- tests/Hash.test.ts
I removed an unused import.
~The test codes use an already compiled SDK.~
~However, the error is displayed in a specific editor.~
~I added '@ts-ignore' so that compilers ignore this code because it is already compiled.~
> Remove an unused import

- package-lock.json
- package.json
- src/modules/net/BOAClient.ts
- tests/BOAClient.test.ts
The name is changed because other data can be stored in addition to voting data.
> Change the name of API from `registerVoteData` to `saveData`

- src/modules/data/Transaction.ts
- src/modules/utils/UInt64.ts
- src/modules/utils/index.ts
- tests/BOAClient.test.ts
UInt64.toString() outputs only in hexadecimal characters.
That's why we need this function.
> Add a function that changes data in UInt64 to string

- package-lock.json
Reverts bpfkorea/boa-sdk-ts#53
It bumped the required version to Node 15, which was not intended.
> Revert "Audit fix for npm"

- .npmignore
If the module is installed in another project, tsconfig.json is required to run the builder.
So, remove tsconfig.json from .npmignore.
> Change `.npmignore` to be built when installed

- src/index.ts
- src/modules/utils/TxPayloadFee.ts
- tests/TxPayloadFee.test.ts
Add a code to calculate the commission of the transaction payload.
The constants used here will be changed to be taken from Agora in the next PR.
Related to #63
> Add the ability to calculate the fee for a transaction payload

- package-lock.json
- package.json
- src/modules/data/BlockHeader.ts
- src/modules/utils/JSONValidator.ts
- tests/Hash.test.ts
Slashing information was recently added to Agora's Block Header.
I apply the change to SDK for this.
> Add information for slashing into `BlockHeader`

- src/modules/net/response/UnspentTxOutput.ts
- tests/BOAClient.test.ts
I added fields (block height, block time, unlock time) to the response on an endpoint /utxo:address
Relates to https://github.com/bpfkorea/stoa/pull/240
> Change UTXO response as Stoa changes

- src/index.ts
- src/modules/net/BOAClient.ts
- src/modules/net/error/ErrorTypes.ts
- tests/BOAClient.test.ts
If an error occurs in HTTP communication, status and statusText are available.
However, it is difficult to use customized messages from a server in SDK.
I create this PR to make the error messages delivered by the server easier to access.
> Enhance error handling to make it easier to access error messages from Stoa

- src/modules/utils/JSONValidator.ts
Two missing fields were added where the JSON schema defines the required fields.
> Fix schema to be used in JSON validator

- src/modules/data/BlockHeader.ts
- tests/Hash.test.ts
We change it for compatibility with Agora.
Also avoid string JSON parsing the Bigint.
The maximum number is 2^52.
As I put it in time, it can be done until 144683.
> Change the block timestamp type to number

- src/modules/common/KeyPair.ts
- tests/KeyPair.test.ts
This function is required to check the received address on HTTP requests.
Relates to https://github.com/bpfkorea/boa-sdk-ts/issues/85
> Add a validate function for Public Key

- src/modules/script/Lock.ts
- src/modules/script/Script.ts
This is the PR that applied the requested modification to the previous PR(#77).
The enumeration value was changed to hexadecimal.
I fixed the style of spacing in the declaration of variables to abide by the rules.
> Style: Fix variable declaration style, change enum values to hexadecimal

- package-lock.json
- package.json
- src/modules/data/DataPayload.ts
- src/modules/utils/Utils.ts
- tests/BOAClient.test.ts
- tests/Hash.test.ts
- tests/TxBuilder.test.ts
I confirmed that the reason for the error mentioned in the issue(#102) is that the order is different 
when it is converted from `string` to `Buffer`. 
So I solved the error and added a test code.
> Change to Big-Endian when input/output as string

- src/modules/data/Transaction.ts
- src/modules/data/TxInput.ts
- src/modules/data/TxOutput.ts
- src/modules/script/Lock.ts
- src/modules/utils/Utils.ts
- tests/Hash.test.ts
I needed a function to return the number of bytes when the transaction was serialized to calculate the fee of the transaction.
And I wanted to get only bytes returned without serialization.
Numeric data are stored in variable sizes when serialized. 
For this purpose, I implemented a function named "Utils.getBytesInNumber".
Relates to https://github.com/bpfkorea/stoa/issues/274
> Add a function that calculates the size of a binary serialized transaction

- package-lock.json
- package.json
The ability to calculate the recently updated transaction size needs to be used in Stoa, so an upgrade to the version is required.
> Upgrade version to 0.0.21

- package-lock.json
- package.json
- src/modules/utils/UTXOManager.ts
The comparison between instances of JSBI should use a static function. However, because they did not do so, they had wrong results.
> Bug fix: The operation of JSBI must use static function

- src/modules/data/Transaction.ts
- src/modules/data/TxInput.ts
- src/modules/data/TxOutput.ts
- src/modules/net/BOAClient.ts
- src/modules/net/response/TrasactionFee.ts
- src/modules/utils/UTXOManager.ts
- src/modules/utils/Utils.ts
- tests/BOAClient.test.ts
- tests/Transaction.test.ts
- tests/Utils.test.ts
Fees increase with the size of the transaction.
When an endpoint is added to Stoa, It will be changed to use the endpoint of Stoa to obtain transaction fees.
Relates to https://github.com/bpfkorea/stoa/issues/274
> Add a function that provides fees for the transactions

- src/modules/net/BOAClient.ts
- tests/BOAClient.test.ts
To facilitate the use of endpoints present in Stoa, I added a function to the SDK that requests them.
> Add the ability to request a pending transaction based on a hash of a transaction

- package-lock.json
- package.json
- src/modules/utils/UTXOManager.ts
This does not make sense because the height of the block can be zero. So I fixed the bug.
> Bug Fix: Cause an error when the block height is 0

- src/modules/data/BitField.ts
- tests/Utils.test.ts
In Agora, BitField was expressed as a string in JSON. I modified it to make it the same as that.
ex)
```
"validators": "[252]",
```
> Change the JSON serialization method of BitField

- src/modules/net/BOAClient.ts
- tests/BOAClient.test.ts
I added the ability to query one transaction using Stoa's endpoint '/transaction/:hash' to the BOAClient.
> Add the ability to request a transaction based on a hash of a transaction

- src/index.ts
- src/modules/common/KeyPair.ts
- src/modules/utils/Utils.ts
- tests/BOAClient.test.ts
- tests/KeyPair.test.ts
- tests/Schnorr.test.ts
- tests/TxBuilder.test.ts
- tests/Utils.test.ts
- tests/Vote.test.ts
I adapt the recently changed class `KeyPair` to SDK.
Related to https://github.com/bosagora/agora/pull/1786
> KeyPair: Remove Seed type, always use SecretKey

- src/modules/vote/Encrypt.ts
- tests/Vote.test.ts
- tests/Votera.test.ts
The encryption key obtained from the Agora Admin page required for the voting process has already been hashed once, so this has been applied.
> Vote: Change how keys are created to encrypt ballots

- package-lock.json
- package.json
- src/modules/common/KeyPair.ts
- src/modules/utils/TxPayloadFee.ts
- src/modules/utils/Utils.ts
- tests/BOAClient.test.ts
- tests/Hash.test.ts
- tests/KeyPair.test.ts
- tests/TxBuilder.test.ts
- tests/ValidationJSON.test.ts
- tests/Vote.test.ts
- tests/Votera.test.ts
Recently, the way Agora's public address is printed as a string has been changed.
I adapted to SDK for this change.
Related to https://github.com/bosagora/agora/issues/1655
> Switch address format from Stellar-style to bech32

- package-lock.json
- package.json
- src/modules/net/BOAClient.ts
- src/modules/vote/BallotData.ts
- src/modules/vote/ProposalData.ts
- src/modules/vote/ProposalFeeData.ts
- tests/BOAClient.test.ts
- tests/Vote.test.ts
- tests/Votera.test.ts
App names should be specified in proposals and votes.
The name of the app included in the voting data will be required during the counting process.
Suggested ID and app name are keys that link different data.
> Add a app's name to proposal data and ballot data

- package-lock.json
- package.json
- src/modules/common/Hash.ts
- src/modules/common/KeyPair.ts
- src/modules/data/DataPayload.ts
- src/modules/data/Transaction.ts
- src/modules/script/Lock.ts
- src/modules/utils/TxBuilder.ts
- src/modules/vote/BallotData.ts
- tests/BOAClient.test.ts
- tests/Hash.test.ts
- tests/KeyPair.test.ts
- tests/Vote.test.ts
- tests/Votera.test.ts
Recently, the method of calculating the hash in Agora has been changed.
As a result, transactions are not being processed normally when they are sent from the wallet.
The newly added code included the size type of the array and the length of the array when the array was hash.
I changed the hash value calculation method to the same as Agora.
> Change the method of calculating hash values to the same as Agora

- src/modules/common/Schnorr.ts
- tests/Schnorr.test.ts
- tests/Vote.test.ts
- tests/Votera.test.ts
I sent the transaction made using SDK to Agora.
A wrong signature message appeared.
When I look up the cause, I find that the position of the Point and Scalar included in the signature has changed and correct it to the same as Agora.
I also included a test code that existed in Agora.
> Fix: Change the order of a point and a scalar for Schnorr signature result

- package-lock.json
- package.json
- src/modules/data/PreImageInfo.ts
- src/modules/utils/JSONValidator.ts
I changed `enroll_key` to `utxo` in JSON validator for PreImageInfo.
And raise it to version 0.0.34 of SDK.
> Fix: JSON validator for PreImageInfo

- src/modules/common/ECC.ts
- src/modules/common/KeyPair.ts
- tests/KeyPair.test.ts
I add a method isValidRandomBytes in KeyPair
It returns true if a valid scalar can be created with given random bytes, otherwise false.
> Add a method isValidRandomBytes in KeyPair

- src/modules/net/BOAClient.ts
- src/modules/script/Lock.ts
- src/modules/vote/ProposalFeeData.ts
React Native has issued a warning as below, so I modified it.
`[Thu Apr 29 2021 16:39:49.260]  WARN     Require cycle: node_modules/boa-sdk-ts/lib/index.js -> node_modules/boa-sdk-ts/lib/modules/data/Block.js -> node_modules/boa-sdk-ts/lib/modules/data/Transaction.js -> node_modules/boa-sdk-ts/lib/modules/data/TxInput.js -> node_modules/boa-sdk-ts/lib/modules/script/Lock.js -> node_modules/boa-sdk-ts/lib/index.js
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Thu Apr 29 2021 16:39:49.270]  WARN     Require cycle: node_modules/boa-sdk-ts/lib/index.js -> node_modules/boa-sdk-ts/lib/modules/vote/ProposalFeeData.js -> node_modules/boa-sdk-ts/lib/index.js
Require cycles are allowed, but can result in uninitialized …
> Fix a circular reference problem

- tests/Block.test.ts
- tests/data/Blocks.sample3.json
Tests have been added for serialization and deserialization of blocks to be used in the stoa.
This was created to allow testing to be carried out before the application of the SDK to the stoa so that more stable development could proceed.
Related to https://github.com/bosagora/boa-sdk-ts/issues/56
> Add test code for block data structures to be used in Stoa

- src/modules/data/DataPayload.ts
- src/modules/utils/JSONValidator.ts
- tests/BOAClient.test.ts
- tests/TxBuilder.test.ts
- tests/ValidationJSON.test.ts
- tests/data/Blocks.sample3.json
When DataPayload is serialized to JSON, change what is represented as hex string to Base64 expression.
This has been changed consistently with other types (Unlock, Lock, etc.).
Related to https://github.com/bosagora/stoa/issues/268
> Change the expression of DataPayload from hex to base64

- package-lock.json
- package.json
- src/index.ts
Some of the data types used in the Votera App have not been exported.
> Export the data types needed for linking with the wallet

- package-lock.json
- package.json
- src/modules/data/TxOutput.ts
- tests/Hash.test.ts
When the output lock is the same, a code that compares with the amount is added.
> Fix the comparison function for sorting the transaction output

- src/modules/vote/BallotData.ts
- tests/Vote.test.ts
- tests/Votera.test.ts
The method of calculating hash values on ballots has been modified.
When strings are processed, hashPart is used.
> Change a computeHash of the BallotData

- package-lock.json
- package.json
- src/index.ts
- src/modules/net/BOAClient.ts
- src/modules/net/response/UnspentTxOutput.ts
- src/modules/utils/TxCanceller.ts
- tests/BOAClient.test.ts
- tests/TxCanceller.test.ts
I implemented a function to cancel transactions that have already been sent.
In order for transactions already sent to be canceled, a new transaction must be created.
The new transaction uses the amount of UTXO used in the previous transaction and the public address as output.
However, the transaction fee should be set higher than the previous transaction.
It uses Agora's processing of double-spending transactions and Stoa's multi UTXO provision.
> Implementing the ability to create a cancellation transaction

- src/modules/utils/SodiumHelper.ts
It was added to avoid creating new object if sodium module was assigned.
> Add a function SodiumHelper.isAssigned()

- src/modules/net/BOAClient.ts
- tests/BOAClient.test.ts
If it already exists in the block, it returns the height of the block and,
if the block has not yet been created, it returns the estimated height is returned.
> Completes the function of requesting the block height according to the block creation time

- src/modules/utils/Utils.ts
If process.env.INIT_CWD and process.env.PWD are undefined, then process.cwd() is used.
I made this to fix the error below in OS Windows 10.
Node Versiion is 14.17.3
`assert.ok(process.env.PWD !== undefined, "Neither `INIT_CWD` nor `PWD` are defined");`
> Update a function Utils.getInitCWD()

- src/modules/common/Signature.ts
It has the ability to check the size of the data left behind.
> Use a function Utils.readBuffer for deserializing in Signature

- src/modules/common/Hash.ts
- tests/Hash.test.ts
Currently, only two are supported. I modified it to allow for several.
> Upgrade to compute more than two buffers at `hashMulti`

- package-lock.json
- package.json
- src/modules/data/TxInput.ts
- src/modules/utils/TxBuilder.ts
- tests/BOAClient.test.ts
- tests/TxBuilder.test.ts
UTXO's hash is Little Endian, so we have to start from the back when comparing this. I fix the bug that is supposed to be compared from the beginning.
> Fix the sort order of transaction inputs.

- src/modules/common/Height.ts
- src/modules/data/BitMask.ts
- src/modules/data/BlockHeader.ts
- src/modules/data/Enrollment.ts
- src/modules/data/Transaction.ts
- src/modules/data/TxInput.ts
- src/modules/data/TxOutput.ts
I reduced duplicate code in computeHash.
I changed to stable Utils.readBuffer().
Function Utils.readBuffer() creates an exception when the end is reached while reading from the buffer.
> Reduce duplicate code in computeHash

- src/index.ts
- src/modules/net/BOAClient.ts
- src/modules/utils/UTXOManager.ts
- src/modules/wallet/Wallet.ts
- tests/BOAClient.test.ts
- tests/UTXOManager.test.ts
- tests/Wallet.test.ts
Currently, SDK requests all UTXO and then extracts the UTXO required.
I changed it like this.
SDK requests Stoa for UTXO with the required amount for a specific address.
Stoa extracts UTXO that meets the conditions and provides it to SDK.
Relates to https://github.com/bosagora/boa-sdk-ts/issues/198
> Add the ability to request UTXO only for the amount required by Stoa

- src/modules/wallet/Wallet.ts
In the process of canceling a transaction, I corrected the code to return the error because it cannot be cancelled if its type is a coinbase.
> Add transaction non-cancellable condition - Coinbase

- src/modules/utils/TxCanceller.ts
- src/modules/wallet/Wallet.ts
- tests/Wallet.test.ts
I processed the transaction to return the reason and code if an error occurred during the creation of the transaction.
> Wallet: Add exception handling to the part where the transaction is built

- package-lock.json
- package.json
- src/modules/utils/TxCanceller.ts
When canceling a transaction, the fee is set 20% higher than that of the previous transaction. At this time, I modified the code to exclude freezing fees.
> Change to consider freezing fees when canceling a transaction
