package-lock.json, package.json
The package `crc` is necessary for the checksum.
The package `@ctrl/ts-base32` is necessary for encode and decode PublicKey.
The `randombytes` is necessary to obtain a random byte array.
=> Add the packages `crc`, `@ctrl/ts-base32`, `randombytes`

src/modules/data/Hash.ts, src/modules/utils/buffer.ts, tests/Hash.test.ts
I added a class of Hash and test code
=> Implement the class of the Hash

src/modules/net/BOAClient.ts, tests/BOASDK.test.ts
I implemented the SDK function to validate preimage.
Related to https://github.com/bpfkorea/stoa/issues/30
=> Implement SDK function to validate pre-image

src/modules/data/PublicKey.ts, src/modules/data/Signature.ts, src/modules/utils/CRC16.ts, tests/CRC16.test.ts, tests/PublicKey.test.ts
I implemented the SDK function to verify the signature
Related to bpfkorea/stoa#30
=> Implement SDK function to verify the signature

.github/workflows/main.yml, .gitignore, .npmignore, package-lock.json, package.json, src/index.ts, tests/BOAClient.test.ts, tests/CRC16.test.ts, tests/Hash.test.ts, tests/PublicKey.test.ts, tsconfig.json
This is a preparation for distribution as an npm package.
I have changed the config files to compile TypeScript and output it to folder lib
I set the main file of the project to lib/index.js or lib/index.ts.
I modified the test code to refer to this main file.
Relates to #13
=> Change the config files to publish on npm

.github/workflows/main.yml, package-lock.json, package.json, src/@types/sodium-javascript/index.d.ts, src/index.ts, src/modules/data/Hash.ts, src/modules/data/PublicKey.ts, tests/Hash.test.ts, tsconfig.json, webpack.config.js
I replaced the sodium library with a version that uses JavaScript and WASM.
I replaced it with JSBI.BigInt for browsers that do not support BigInt.
~I replaced writeBigUInt64LE with writeUInt32LE~
Replace with using bit operation instead of writeBigUInt64LE because some browsers do not support writeBigUInt64LE
I create a library for the browsers using the webpack
I did a test on four kinds of browsers. I have confirmed that all of them are operating normally.
**Chrome**
**Safari**
**FireFox**
**Microsoft Edge**
Test code is https://github.com/MichaelKim20/boa-sdk-ts-test
``` JavaScript
writeMessage("[Test for Hash]");
var h = BoaSdk.hash(stringToUint8Array('abc'));
if (h.toString() === '0x239900d4ed8623b95a92f1dba88ad31895cc3345ded552c22d79ab2a39c5877' + …
```
=> Create a library that works with a browser

package-lock.json, package.json
Upgrade the version of the npm package.
=> Upgrade the version of the npm package.

package-lock.json, package.json, src/modules/net/BOAClient.ts, tests/BOAClient.test.ts
Inquiring block heights presently or in a specific future time
Shell function to convert from time to height
Relates to Issue #16
=> Implement getHeightAt in SDK

.github/workflows/main.yml, .gitignore, package-lock.json, package.json, typedoc.js
SDK documents are automatically generated when code is pushed.
Related to #22
=> Create the documentation with typedoc

README.md
=> Add SDK Document Link to README.md

tests/BOAClient.test.ts, tests/KeyPair.test.ts
I fixed style, wrong spaces, and semicolons
=> Style fix: wrong spaces and semicolons

README.md, tests/BOAClient.test.ts
I changed because errors are being displayed in certain editors.
=> Sets the data type of the parameter in the Promise.catch callback function

src/index.ts, src/modules/data/Hash.ts, src/modules/data/KeyPair.ts, src/modules/data/PreImage.ts, src/modules/data/Signature.ts, src/modules/data/Validator.ts, src/modules/net/BOAClient.ts, src/modules/net/Request.ts, src/modules/utils/CRC16.ts, src/modules/utils/index.ts, tests/BOAClient.test.ts, tests/CRC16.test.ts, tests/Hash.test.ts, tests/KeyPair.test.ts
I changed the order of the import.
> I first imported SDK files.
I changed from " to '.
I added `index.ts` to `src/modules/utils`.
=> Change package importing to consistent code

package-lock.json, package.json, src/index.ts, src/modules/data/Hash.ts, src/modules/data/KeyPair.ts, src/modules/data/Signature.ts, src/modules/data/Transaction.ts, src/modules/data/TxInput.ts, src/modules/data/TxOutput.ts, src/modules/net/BOAClient.ts, tests/BOAClient.test.ts, tests/Hash.test.ts
I added information to access Agora to BOAClient
I added the ability to create and send a voting transaction
I have already done PR #39  on the issue.
However, after thinking more about it, I have created a new PR.
Related to #17
=> Add the ability to create and send a voting data

src/modules/data/KeyPair.ts, src/modules/data/PreImage.ts, src/modules/data/Transaction.ts, src/modules/data/Validator.ts, src/modules/net/BOAClient.ts, src/modules/net/Request.ts, src/modules/utils/SodiumHelper.ts
Exclude variables, functions, interfaces, and classes that are used internally only from documents.
=> Set the symbols to be excluded from the document

src/modules/data/Transaction.ts, src/modules/data/TxInput.ts, tests/BOAClient.test.ts, tests/Hash.test.ts
previous to `utxo` & remove the `index`
Related to #49
=> Synchronize with Transaction Input Stoa

package.json, src/index.ts, src/modules/data/DataPayload.ts, src/modules/data/Transaction.ts, src/modules/net/BOAClient.ts, src/modules/utils/Utils.ts, tests/BOAClient.test.ts, tests/Hash.test.ts
Add a new type of `DataPayload`.
Related to #49
=> Stoa's Transaction.payload Synchronized

src/modules/data/DataPayload.ts, src/modules/data/Hash.ts, src/modules/data/KeyPair.ts, src/modules/data/Signature.ts, src/modules/data/Transaction.ts, src/modules/data/TxOutput.ts, src/modules/net/BOAClient.ts, src/modules/net/response/PreImage.ts, src/modules/net/response/Validator.ts, src/modules/utils/CRC16.ts, src/modules/utils/Utils.ts
I delete the type from documents because the type of parameter can be omitted in the typescript.
I changed other documents properly.
=> Fix document

src/index.ts, src/modules/net/BOAClient.ts, src/modules/net/response/UnspentTxOutput.ts, tests/BOAClient.test.ts
We need a function that returns the UTXOs for a given PublicKey.
It requests Stoa for public key's UTXOs and returns unspent UTXOs.
Related to #51
=> Implement get UTXOs function

src/index.ts, src/modules/utils/UTXOManager.ts, tests/UTXOManager.test.ts
This calculates the sum of the UTXO amounts.
This also provides UTXOs for the required amount.
This is dependent on PR #67 
Related to #63
=> Implement a class for managing UTXO

src/index.ts, src/modules/utils/TxBuilder.ts, tests/TxBuilder.test.ts
Add utilities that build transactions easily and clearly.
In the future, the UTXO used here will be used from Stoa.
Related to #63
=> Add a class to build a transaction

src/modules/net/BOAClient.ts, tests/BOAClient.test.ts
I apply transaction builder and fee calculation to BOAClient.
This is dependent on PR #64 and PR #65 and PR #68 
From now on, I plan to include using UTXO provided by Stoa.
And I am planning to conduct an actual test with Agora.
---
I was able to request UTXO from Stoa, extract as much of the UTXO received using UTXOManager, 
and use the transaction builder to create a transaction using the extracted UTXO as input.
I have completed the function of sending this transaction to Agora.
To test this process, I realized that I needed a change in the existing test code. 
So I went on with the following work.
1. I changed the Stoa Fake Server for testing into a class.
2. I implemented a similar type of Agora fake server.
Since then, I applied transaction builder and fee calculation to BOAClient. …
=> Apply transaction builder and fee calculation to BOAClient

src/index.ts, src/modules/common/ECC.ts, src/modules/common/Schnorr.ts, src/modules/data/Hash.ts, src/modules/data/KeyPair.ts, src/modules/utils/Utils.ts, tests/ECC.test.ts, tests/Schnorr.test.ts, tests/Utils.test.ts
I Implemented some modules related to Schnorr signatures.
This is a TypeScript translation of Agora's corresponding module.
https://github.com/bpfkorea/agora/blob/297c6a3a3c7388a47d07c00c4194194b467b7bae/source/agora/common/crypto/ECC.d
https://github.com/bpfkorea/agora/blob/297c6a3a3c7388a47d07c00c4194194b467b7bae/source/agora/common/crypto/Schnorr.d
Relates to #74
=> Implement Schnorr signature

package.json, src/modules/data/BlockHeader.ts, src/modules/utils/JSONValidator.ts, tests/Hash.test.ts
Synchronize Agora changes
https://github.com/bpfkorea/agora/pull/1437
Related to
https://github.com/bpfkorea/stoa/issues/241
=> Add a timestamp in  the block header

src/modules/common/KeyPair.ts, tests/KeyPair.test.ts
I think we need to verify the Seek key that the users entered. So I add the function.
=> Add a validate function for Seed Key

.github/workflows/main.yml, src/index.ts, src/modules/data/Transaction.ts, src/modules/data/TxInput.ts, src/modules/data/TxOutput.ts, src/modules/script/Lock.ts, src/modules/script/Opcodes.ts, src/modules/script/Script.ts, src/modules/utils/JSONValidator.ts, src/modules/utils/TxBuilder.ts, tests/BOAClient.test.ts, tests/Hash.test.ts, tests/OpCode.test.ts, tests/Script.test.ts, tests/TxBuilder.test.ts, tests/ValidationJSON.test.ts
1. Changed the structure of the Transaction
Replace Signature of TxInput with Unlock, replace PublicKey of TxOutput with Lock
2. Changed signer of Transaction
3. Changed TxBuilder
4. Added a module Lock
5. Added a module Script, Opcodes
It was made for a flash-layer of Agora.
I think we should create a temporary branch similar to Agora.
Depend on #75 
Related to #74
=> Apply classes Lock, Unlock and add Script for multi-signature, flash layer

tests/BOAClient.test.ts
I created this to simplify the complexity of the asynchronous function and ensure that accurate testing is done.
And I refer to the method shown in the link below.
https://www.testim.io/blog/testing-promises-using-mocha/
=> Reorganize test code for simple and clear using async / await

src/index.ts, src/modules/net/BOAClient.ts, src/modules/net/error/ErrorTypes.ts
I changed the code to make the error processing function export for use in Stoa.
=> Export a function for network error handler

src/modules/common/ECC.ts, src/modules/common/Hash.ts, src/modules/common/KeyPair.ts, src/modules/common/Signature.ts, src/modules/utils/CRC16.ts
It is strange that an asset is being used in the library. So I modified the code to throw an exception.
=> Replace with throwing exceptions instead of assert in the library

package-lock.json, package.json
I upgrade the version to prepare for merge with branch flash-layer.
=> Upgrade version to 0.0.14

package-lock.json, package.json, src/index.ts, src/modules/data/Transaction.ts, src/modules/data/TxInput.ts, src/modules/data/TxOutput.ts, src/modules/script/Lock.ts, src/modules/script/Opcodes.ts, src/modules/script/Script.ts, src/modules/utils/JSONValidator.ts, src/modules/utils/TxBuilder.ts, tests/BOAClient.test.ts, tests/Hash.test.ts, tests/OpCode.test.ts, tests/Script.test.ts, tests/TxBuilder.test.ts, tests/ValidationJSON.test.ts
I merge the flash-layer branch into v0.x.x
=> Merge flash-layer branch into v0.x.x

.gitignore, package-lock.json, package.json, src/modules/data/Transaction.ts, src/modules/data/TxInput.ts, src/modules/utils/JSONValidator.ts, tests/BOAClient.test.ts, tests/Hash.test.ts, tests/TxBuilder.test.ts, tests/ValidationJSON.test.ts
Add a lock_height that was deleted when the branch flash-layer was revert
=> Add lock_height in the class Transaction

src/modules/utils/TxBuilder.ts, tests/BOAClient.test.ts, tests/TxBuilder.test.ts
Recently, Agora added the ability to apply data payloads and transaction fees.
I have thus implemented the ability to input fees into SDK.
Relates to #104
=> TxBuilder: Implement the ability to enter the fee

src/modules/common/ECC.ts
I corrected an invalid return (Hash -> Point)
=> Fix bug: Correct an invalid return

package-lock.json, package.json
I am upgrading the version to make the newly added transaction fee calculation function available.
=> Upgrade version to 0.0.23

src/index.ts, src/modules/net/BOAClient.ts, src/modules/net/response/Types.ts, tests/BOAClient.test.ts
Stoa has endpoints made for wallets. I added this to SDK for easy use.
=> Wallet: Add functions for wallet using the endpoints provided by Stoa

package-lock.json, package.json, src/modules/utils/TxBuilder.ts, tests/BOAClient.test.ts, tests/TxBuilder.test.ts
I changed the refund output to be at the front of the array according to the changes in Agora below.
https://github.com/bpfkorea/agora/pull/1664
Relates to https://github.com/bpfkorea/stoa/issues/280
=> TxBuilder: Reposition the refund output to the front

package-lock.json, package.json, tests/BOAClient.test.ts
The package `randombytes` use package `crypto` internally.
I have carried out this task to remove the circulation reference from BOA wallet.
=> Change to use libsodium instead of package randombytes

package-lock.json, package.json, src/modules/data/BlockHeader.ts, src/modules/utils/JSONValidator.ts
Synchronize Agora changes : [bpfkorea/agora#1693](https://github.com/bpfkorea/agora/pull/1693)
=> BlockHeader: Change `timestamp` to `time_offset`

src/modules/common/KeyPair.ts, tests/BOAClient.test.ts, tests/KeyPair.test.ts, tests/Schnorr.test.ts, tests/TxBuilder.test.ts
I made this to solve issue #127
=> KeyPair: Change the KeyPair from Ed25519 to Curve25519

src/index.ts, src/modules/net/BOAClient.ts, src/modules/utils/Utils.ts, src/modules/utils/VarInt.ts, src/modules/vote/BallotData.ts, src/modules/vote/Encrypt.ts, src/modules/vote/ProposalData.ts, src/modules/vote/ProposalFeeData.ts, tests/BOAClient.test.ts, tests/Utils.test.ts, tests/Vote.test.ts, tests/Votera.test.ts
This is the code that defines the data related to Votera's proposal and voting.
This includes serialization and deserialization codes for data as binaries.
Related to #105
=> Add voting data structures

src/modules/vote/BallotData.ts, src/modules/vote/Encrypt.ts, src/modules/vote/ProposalData.ts, src/modules/vote/ProposalFeeData.ts, src/modules/wallet/LinkData.ts, tests/Vote.test.ts, tests/Votera.test.ts
I defined the data that will be used to link data between apps to send transactions to Agora via wallet in Votera app.
And I added the function to return the data to JSON.
It is dependent on PR #121
Relates to https://github.com/bpfkorea/boa-sdk-ts/issues/106
=> Establish a protocol for transferring data between Votera app and wallet app

.github/workflows/documentation.yml
=> Fix build documentation ci

package-lock.json, package.json, src/modules/common/KeyPair.ts, tests/KeyPair.test.ts
I added a code to check whether the key made of input data is valid as Scalar, Point.
=> Keys: Add a validation code when a key is generated

src/modules/data/Transaction.ts
This is a follow-up to the Agora change.
=> Add a transaction type named `Coinbase`

package-lock.json, package.json, src/modules/common/Hash.ts, src/modules/vote/BallotData.ts, tests/ECC.test.ts, tests/Vote.test.ts, tests/Votera.test.ts
This is a follow-up to Agora.
I calculated the hash value of VoterCard in D language and checked if the result was the same as the value calculated in TypeScript.
=> Change the expires of the VoterCard to a string

src/modules/vote/Encrypt.ts
[TypeError: "list" argument must be an Array of Buffers]
=> Fix Error in React Native

package-lock.json, package.json, src/modules/data/Transaction.ts, src/modules/data/TxInput.ts, src/modules/data/TxOutput.ts, src/modules/utils/TxBuilder.ts, tests/BOAClient.test.ts, tests/Hash.test.ts, tests/data/Blocks.sample3.json
I create this to apply to the change of Agora.
https://github.com/bosagora/agora/pull/2071
=> Sort the transaction inputs and outputs

src/modules/common/Hash.ts, src/modules/common/Height.ts, src/modules/common/KeyPair.ts, src/modules/common/Schnorr.ts, src/modules/common/Signature.ts, src/modules/data/BitField.ts, src/modules/data/Block.ts, src/modules/data/BlockHeader.ts, src/modules/data/DataPayload.ts, src/modules/data/Enrollment.ts, src/modules/data/Transaction.ts, src/modules/data/TxInput.ts, src/modules/data/TxOutput.ts, src/modules/script/Lock.ts, src/modules/vote/ProposalFeeData.ts, tests/Serialize.test.ts
I added the ability to serialize and deserialize components of block data. 
This is necessary to solve the issue below.
https://github.com/bosagora/stoa/issues/336
=> Add function of serialization and deserialization

src/index.ts, src/modules/vote/EncryptionKey.ts, tests/Vote.test.ts
The encryption key was added with the validator's public key and signature. 
This class was created to facilitate the verification of signatures.
=> Add a class that defines encryption key

package-lock.json, package.json, src/modules/data/TxOutput.ts, tests/BOAClient.test.ts, tests/Hash.test.ts, tests/Transaction.test.ts
The size of TxOutput.type is 4 bytes.
=> Fix the size of TxOutput.type

package-lock.json, package.json, src/modules/utils/UTXOManager.ts, tests/UTXOManager.test.ts
When computing the sum of UTXO, I modified it to consider Coinbase.
=> Fix an error when type of transaction output is Coinbase

src/modules/common/Hash.ts, src/modules/common/Schnorr.ts, src/modules/data/Transaction.ts, src/modules/script/Lock.ts, src/modules/vote/ProposalData.ts
It has the ability to check the size of the data left behind.
=> Use a function Utils.readBuffer for deserializing

.gitignore, .vscode/settings.json
I made this to automatically apply the code format in Visual Studio Code.
=> Automates code styles from Visual Studio Code

src/modules/data/Block.ts, src/modules/data/BlockHeader.ts, src/modules/data/Transaction.ts
I create this PR to simplify the code.
=> Apply the function iota to other modules

src/modules/vote/BallotData.ts
Voters can be rejected under certain conditions.
=> Adds a ballot separation value

src/index.ts, src/modules/net/BOAClient.ts, src/modules/net/response/Types.ts, src/modules/utils/UTXOManager.ts, src/modules/wallet/Wallet.ts, tests/Wallet.test.ts
I added a function to the class wallet to make freezing and unfreezing easier.
=> Add  functions freeze and unfreeze

src/modules/wallet/Wallet.ts, tests/BOAClient.test.ts, tests/Utils.ts, tests/Wallet.test.ts, tsconfig.json
I isolated the commonly used function in the test code.
=> Wallet: Separate fake agora, stoa and sample data needed for testing into separate files

src/modules/net/BOAClient.ts, tests/BOAClient.test.ts, tests/Utils.ts
Returns the time for the block height.
Returns its creation time if the block is already created.
Otherwise, it returns the expected creation time.
=> Add a method getHeightToTime() in BOAClient

src/modules/wallet/WalletTxBuilder.ts
I create this to solve Issue #291 
I carefully checked the pattern of using WalletTxBuilder in Wallet.
This is because the account object is shared on two screens.
This will be resolved by initializing all data on the WalletTxBuilder object used at the end of the screen and deleting the event.
However, I added an exception handler so that even if an exception is made by the library's usage method, it can be resolved.
=> WalletTxBuilder: Change to recalculate when an exception occurs

src/modules/wallet/WalletTxBuilder.ts
This was created to solve issues https://github.com/bosagora/boa-sdk-ts/issues/309 and https://github.com/bosagora/boa-sdk-ts/issues/310.
The fee rate is periodically requested from the server only when the user does not manually change the fee value.
=> Improve the fee rate once a minute to bring it from Stoa if necessary.

src/index.ts, src/modules/wallet/Types.ts, src/modules/wallet/WalletTxBuilder.ts, src/modules/wallet/WalletUtil.ts, tests/wallet/WalletTxBuilder.test.ts, tests/wallet/WalletUtil.test.ts
Create a transaction to cancel the pending transaction.
=> WalletCancelBuilder: Add the builder of transactions to cancel pending transaction

package-lock.json, package.json, src/modules/wallet/WalletWatcher.ts, tests/wallet/WalletWatcher.test.ts
This is a PR to respond to Stoa's modifications.
https://github.com/bosagora/stoa/pull/494
=> WalletWatcher: Remove "onNewBlock()", add transaction hash and type("pending", "confirm")

src/modules/wallet/Account.ts
I changeed the event to occur when loading account info
=> AccountContainer: Change the event to occur when loading account info

src/modules/wallet/Types.ts, src/modules/wallet/WalletTxBuilder.ts, tests/wallet/WalletTxBuilder.test.ts
WalletCancelBuilder: Add verification of a transaction that has already been canceled.
=> WalletCancelBuilder: Add verification of a transaction that has already been canceled

package-lock.json, package.json, src/modules/data/BlockHeader.ts, src/modules/utils/JSONValidator.ts, tests/Hash.test.ts, tests/Serialize.test.ts, tests/data/Blocks.sample3.json
It responds to changes in the agora.
https://github.com/bosagora/agora/pull/2676
=> Remove `time_offset` in `BlockHeader`

package-lock.json, package.json, src/modules/wallet/WalletTxBuilder.ts, tests/wallet/WalletTxBuilder.test.ts
I added a function that provides an overview of the transaction to be canceled.
=> Add a function in the class WalletCancelBuilder

package-lock.json, package.json, src/modules/wallet/Account.ts, tests/wallet/Account.test.ts
Create this so that the entire balance can be calculated when the account is deleted.
=> Change to calculate the total balance when calling function checkBalance

src/modules/common/Hash.ts, src/modules/common/Height.ts, src/modules/common/Signature.ts, src/modules/data/BitMask.ts, src/modules/data/Block.ts, src/modules/data/BlockHeader.ts, src/modules/data/Enrollment.ts, tests/Serialize.test.ts
This was created to solve the issue #325
=> Add a function that calculates the size of the block

package-lock.json, package.json, src/modules/wallet/WalletWatcher.ts
Wallet has a part where the balance is checked periodically every certain time.
Events that occur forcibly there are removed.
=> Remove event that occur in unnecessary situations.(CHANGE_BALANCE)

src/index.ts, src/modules/data/Constant.ts, src/modules/utils/TxBuilder.ts, src/modules/utils/TxCanceller.ts, src/modules/wallet/EventDispatcher.ts, src/modules/wallet/Types.ts, src/modules/wallet/Wallet.ts, src/modules/wallet/WalletTxBuilder.ts, tests/BOAClient.test.ts, tests/TxBuilder.test.ts, tests/TxCanceller.test.ts, tests/Utils.ts, tests/wallet/Wallet.test.ts, tests/wallet/WalletClient.test.ts, tests/wallet/WalletTxBuilder.test.ts
Freezing TXs now have to include SlashAmountPenatly amount of fee for each Freeze output they have
It's a related PR in Agora.
https://github.com/bosagora/agora/pull/2597
=> Apply freezing fee
